### ISSUE TITLE
Update to Jekyll 4

### ISSUE THREAD

**Issue by Niek** [chrisrhymes/bulma-clean-theme#26]
From a fresh Jekyll install:
```bash
$ bundle
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "jekyll":
  In snapshot (Gemfile.lock):
    jekyll (= 4.0.0)

  In Gemfile:
    jekyll (~> 4.0.0)

    bulma-clean-theme was resolved to 0.6, which depends on
      jekyll (~> 3.8)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by chrisrhymes** [comment]
Hi @Niek. I would like to keep the theme compatible with GitHub pages and it looks like that is still using Jekyll 3.8 according to the runtime dependencies: https://rubygems.org/gems/github-pages

**Comment by Niek** [comment]
Makes sense, thanks for explaining!

**Comment by eheinrich** [comment]
Hi @chrisrhymes, I'm starting a new Jekyll site and would love to use this theme, it looks great! The site that I'm starting will **not** be deployed on GitHub Pages, and I would like to use Jekyll v4. I wanted to check in on this issue since it's been a couple years since it's been updated. Have plans to allow the theme to work with Jekyll v4 changed during that time? I understand that that effort has been blocked on the GitHub Pages gem not supporting it yet, and that you want to keep the theme compatible with that gem, but [this issue](https://github.com/github/pages-gem/issues/651) makes it seem like they won't be updating to Jekyll v4 any time soon (or at all? it's unclear...).

As part of this, I was wondering if you would be open to updating the version range of Jekyll in this project's gemspec to something like `spec.add_runtime_dependency "jekyll", ">= 3.9", "< 4.3.0"`? That way, for people like me who are not deploying to GH Pages, or for those who are using GH Actions instead of the GH Pages gem to deploy their site to GH Pages, a newer version of Jekyll can be used. And for those that are using the GH Pages gem, the dependency should resolve to `3.9`. To check if this theme would work with v4, I cloned this repo, updated the gemspec as described, and ran the hot reload server. Just from some quick preliminary testing, the site seemed to work as I would expect using Jekyll version `4.2.1`.
