### ISSUE TITLE
tag release for remote_theme use

### ISSUE THREAD

**Issue by mnyrop** [chrisrhymes/bulma-clean-theme#60]
hello,

would you consider tagging a release of the theme on github (e.g., `v0.9.2`, according to the `gemspec`)? i'm currently using the theme as a `remote_theme` on github pages which works great, but having my site build off of your `master` branch (which is subject to change) instead of a static release seems unnecessarily volatile.

thanks for your consideration!

**Comment by chrisrhymes** [comment]
Hello,

You can use the theme as a gem theme and version it that way rather than forking the repo. This is what I do with my [personal website](https://github.com/chrisrhymes/chrisrhymes.github.io/blob/master/Gemfile#L2). 

Please see the [Jekyll documentation](https://jekyllrb.com/docs/themes/) for more information on Gem based themes.

**Comment by mnyrop** [comment]
@chrisrhymes Github pages doesn't allow external gem-based themes, since it runs Jekyll in `safe` mode. The only way to achieve this is through the `remote_theme` configuration, which looks for a Github repo to use *as* a gem-based theme. Tagging a release of your gem on Github (in addition to rubygems) would allow versioning with this feature.

See documentation: https://www.siteleaf.com/blog/remote-themes/

**Comment by chrisrhymes** [comment]
Hi @mnyrop thanks for the info! I have now tagged [0.9.2](https://github.com/chrisrhymes/bulma-clean-theme/releases/tag/v0.9.2).

**Comment by mnyrop** [comment]
Awesome, thank you!
